name: Update lockfile
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  lockfile:
    name: "Update lockfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v27
